ci: add reusable workflow + update main workflow

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -13,17 +13,23 @@ jobs:
       - uses: actions/checkout@v3
 
       - name: Lint
-        run: make lint
+        id: lint
+        run: make lint || true  # Run lint and allow it to modify files without failing
 
-      # Check if there are any changes after linting
       - name: Commit and Push Changes
+        if: success()
         run: |
           if [[ `git status --porcelain` ]]; then
             git config --global user.name "github-actions[bot]"
             git config --global user.email "github-actions[bot]@users.noreply.github.com"
             git add .
-            git commit -m "Apply automatic formatting via lint"
+            git commit -m "Apply automatic formatting via terragrunt-hclfmt"
             git push origin main
           else
             echo "No changes to commit"
           fi
+
+      # Re-run lint to confirm all files are now correctly formatted
+      - name: Re-run Lint
+        if: success()
+        run: make lint
